import { useState } from "react";
import Head from "next/head";

import styles from "@/styles/Home.module.css";

import Person from "@/components/person";
import Button from "@/components/button";

import { getProject, getUserPromises } from "@/services/jira";
import { reduceByIndexOrder } from "@/helpers";
import { JIRA_USERS, NAMES } from "@/constants";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { signIn, signOut, useSession } from "next-auth/react";

let counter = 0;

type HomeProps = {
  project: Project;
  users: {
    [K in keyof JIRA_USERS]: User;
  };
};

export default function Home({ project, users }: HomeProps) {
  const {data: session, status} = useSession();
  const [currentUser, setCurrentUser] = useState<string>(NAMES[0]);
  const [end, setEnd] = useState(false);
  const [start, setStart] = useState(false);

  if (status === 'loading') {
    return (
      <>
        Loading...
      </>
    )
  }

  if (!session) {
    return (
      <>
        <div className={styles.container}>
          <h1 className={styles.title}>Standup App</h1>
          <Button onClick={() => signIn()} centered>Sign in</Button>
        </div>
      </>
    )
  }

  const handleClick = () => {
    counter++;

    if (counter > NAMES.length - 1) {
      return setEnd(true);
    }

    setCurrentUser(NAMES[counter]);
  };

  if (!start) {
    return (
      <>
        <h2 className={styles.projectName}>{project.name}</h2>
        <div className={styles.container}>
          <h1 className={styles.title}>Are you ready?</h1>
          <img
            className={styles.entryPhoto}
            src="https://i.gifer.com/origin/0b/0b2157f45bff10c821635c1749ad47d1_w200.gif"
          ></img>
          <Button onClick={() => setStart(true)} centered>
            Begin Stand Up
          </Button>
          <Button onClick={() => signOut()} centered>
            Sign out
          </Button>
        </div>
      </>
    );
  }

  if (end) {
    return (
      <>
        <h2 className={styles.projectName}>{project.name}</h2>
        <div className={styles.container}>
          <h1 className={styles.title}>Thank you!</h1>
          <img
            className={styles.mainPhoto}
            src="https://img1.picmix.com/output/pic/normal/5/3/5/6/7416535_1f01a.gif"
          />
          <p className={styles.note}>You may now close this tab</p>
        </div>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2 className={styles.projectName}>{project.name}</h2>
      <main className={styles.container}>
        <div>
          <Person
            data={users[currentUser as keyof JIRA_USERS]}
            onClick={handleClick}
          />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const session = await getServerSession(context.req, context.res, authOptions)

  return Promise.all([getProject(), ...getUserPromises()]).then(
    ([data, ...users]) => {
      return {
        props: {
          username: session?.user?.name || null,
          project: data,
          users: reduceByIndexOrder(JIRA_USERS, users),
        },
      };
    }
  );
}
